"""add github_prs.

Revision ID: 6e7e78abc3a2
Revises: 6788441ce2c4
Create Date: 2026-06-04 17:38:41.074206

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e7e78abc3a2"
down_revision: str | Sequence[str] | None = "6788441ce2c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_prs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("backend_id", sa.String(length=36), nullable=False),
        sa.Column("github_id", sa.String(length=255), nullable=False),
        sa.Column("repo_owner", sa.String(length=255), nullable=False),
        sa.Column("repo_name", sa.String(length=255), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("draft", sa.Boolean(), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("author_avatar_url", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("base_ref", sa.String(length=255), nullable=False),
        sa.Column("head_ref", sa.String(length=255), nullable=False),
        sa.Column("head_sha", sa.String(length=64), nullable=False),
        sa.Column("additions", sa.Integer(), nullable=False),
        sa.Column("deletions", sa.Integer(), nullable=False),
        sa.Column("changed_files", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("backend_id", "github_id"),
    )
    op.create_index("ix_github_prs_backend_id", "github_prs", ["backend_id"], unique=False)
    op.create_index("ix_github_prs_role", "github_prs", ["role"], unique=False)
    op.create_index("ix_github_prs_state", "github_prs", ["state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_github_prs_state", table_name="github_prs")
    op.drop_index("ix_github_prs_role", table_name="github_prs")
    op.drop_index("ix_github_prs_backend_id", table_name="github_prs")
    op.drop_table("github_prs")
    # ### end Alembic commands ###
